/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.identifiants;

import com.solutec.Identifiants;
import com.solutec.IdentifiantsBD;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author esic
 */
public class IdentifiantsSwing extends javax.swing.JFrame {

    /**
     * Creates new form Identifiants
     */
    
    public IdentifiantsSwing() {
        initComponents();
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        labelLogin = new javax.swing.JLabel();
        labelMdp = new javax.swing.JLabel();
        chLogin = new javax.swing.JTextField();
        chMdp = new javax.swing.JTextField();
        Consulter = new javax.swing.JButton();
        Supprimer = new javax.swing.JButton();
        Modifier = new javax.swing.JButton();
        Ajouter = new javax.swing.JButton();
        chNvxLogin = new javax.swing.JTextField();
        chNvxMdp = new javax.swing.JTextField();
        Modifier2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Simplified Arabic", 0, 24)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        labelLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelLogin.setText("Login");

        labelMdp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelMdp.setText("Mot de Passe");

        chLogin.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        chLogin.setText("Entrez le login");

        chMdp.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        chMdp.setText("Entrez le mot de passe");

        Consulter.setBackground(new java.awt.Color(204, 204, 255));
        Consulter.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        Consulter.setForeground(new java.awt.Color(0, 153, 153));
        Consulter.setText("Consulter");
        Consulter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsulterActionPerformed(evt);
            }
        });

        Supprimer.setBackground(new java.awt.Color(204, 204, 255));
        Supprimer.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        Supprimer.setForeground(new java.awt.Color(0, 153, 153));
        Supprimer.setText("Supprimer");
        Supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerActionPerformed(evt);
            }
        });

        Modifier.setBackground(new java.awt.Color(204, 204, 255));
        Modifier.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        Modifier.setForeground(new java.awt.Color(0, 153, 153));
        Modifier.setText("Modifier");
        Modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierActionPerformed(evt);
            }
        });

        Ajouter.setBackground(new java.awt.Color(204, 204, 255));
        Ajouter.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        Ajouter.setForeground(new java.awt.Color(0, 153, 153));
        Ajouter.setText("Ajouter");
        Ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterActionPerformed(evt);
            }
        });

        chNvxLogin.setText("Nouveau login");
        chNvxLogin.setEnabled(false);
        chNvxLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chNvxLoginActionPerformed(evt);
            }
        });

        chNvxMdp.setText("Nouveau Mot de passe");
        chNvxMdp.setEnabled(false);
        chNvxMdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chNvxMdpActionPerformed(evt);
            }
        });

        Modifier2.setBackground(new java.awt.Color(204, 204, 255));
        Modifier2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        Modifier2.setForeground(new java.awt.Color(0, 153, 153));
        Modifier2.setText("Confirmer modifs");
        Modifier2.setEnabled(false);
        Modifier2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modifier2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(Consulter)
                        .addGap(75, 75, 75)
                        .addComponent(Supprimer)
                        .addGap(73, 73, 73)
                        .addComponent(Modifier)
                        .addGap(81, 81, 81)
                        .addComponent(Ajouter))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMdp))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chLogin)
                            .addComponent(chMdp, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chNvxMdp)
                            .addComponent(Modifier2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chNvxLogin))))
                .addContainerGap(267, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(Modifier2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chNvxLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(labelMdp))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chMdp, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                            .addComponent(chNvxMdp))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Consulter, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConsulterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsulterActionPerformed
        // TODO add your handling code here:
       
        IdentifiantsBD identifiantsBD = new IdentifiantsBD();
        ArrayList<Identifiants> listeIdentifiants = new ArrayList<>();
        listeIdentifiants.addAll(identifiantsBD.getListIdentifiants());
        String tampon = new String();
        for (int i = 0; i < listeIdentifiants.size(); i++) {
        tampon = tampon +("Login: "+ listeIdentifiants.get(i).getLogin()+"\n"+"Mdp: "+ listeIdentifiants.get(i).getMdp()+"\n \n");
      }
        
        jTextArea1.setText(tampon);
        
    }//GEN-LAST:event_ConsulterActionPerformed

    private void SupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerActionPerformed
        // TODO add your handling code here:
        IdentifiantsBD identifiantsBD = new IdentifiantsBD();
        boolean test;
        test = identifiantsBD.supprimerIdentifiant(chLogin.getText());
        
         if (test==false){
       
        JOptionPane.showMessageDialog(rootPane, "Echec lors de la suprresion ! Utilisateur introuvable",  "Erreur", JOptionPane.ERROR_MESSAGE);
        }
         
         if (test){
       
        JOptionPane.showMessageDialog(rootPane, "Suppresion réussie",  "Info", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_SupprimerActionPerformed

    private void ModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(rootPane, "TEST");
       //jTextArea1.setText(chNvxLogin.getText()+chNvxMdp.getText());
     
       chNvxLogin.setEnabled(true);
       chNvxMdp.setEnabled(true);
       Modifier2.setEnabled(true);
       Modifier.setEnabled(false);
       chLogin.setEnabled(false);
       chMdp.setEnabled(false);
       Ajouter.setEnabled(false);
       Supprimer.setEnabled(false);
       Consulter.setEnabled(false);
     
       //IdentifiantsBD identifiantsBD = new IdentifiantsBD();
       //identifiantsBD.modifierIdentifiant(chLogin.getText(), chNvxLogin.getText(), chNvxMdp.getText());
       
       
       
    }//GEN-LAST:event_ModifierActionPerformed

    private void AjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterActionPerformed
        // TODO add your handling code here:
        IdentifiantsBD identifiantsBD = new IdentifiantsBD();
        boolean test;
        test = identifiantsBD.ajouterIdentifiant(chLogin.getText(), chMdp.getText());
        if (test==false){
       
        JOptionPane.showMessageDialog(rootPane, "Utilisateur déjà existant !",  "Erreur", JOptionPane.ERROR_MESSAGE);
        }
          if (test){
       
        JOptionPane.showMessageDialog(rootPane, "Ajout réussi",  "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_AjouterActionPerformed

    private void chNvxMdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chNvxMdpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chNvxMdpActionPerformed

    private void chNvxLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chNvxLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chNvxLoginActionPerformed

    private void Modifier2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modifier2ActionPerformed
        // TODO add your handling code here:
       
       chNvxLogin.setEnabled(false);
       chNvxMdp.setEnabled(false);
       Modifier2.setEnabled(false);
       IdentifiantsBD identifiantsBD = new IdentifiantsBD();
       boolean test;
       test = identifiantsBD.modifierIdentifiant(chLogin.getText(), chNvxLogin.getText(), chNvxMdp.getText());
       chLogin.setEnabled(true);
       chMdp.setEnabled(true);
       Modifier.setEnabled(true);
       Ajouter.setEnabled(true);
       Supprimer.setEnabled(true);
       Consulter.setEnabled(true);
        if (test==false){
       
        JOptionPane.showMessageDialog(rootPane, "Utilisateur déjà existant !",  "Erreur", JOptionPane.ERROR_MESSAGE);
        }
       
         if (test){
       
        JOptionPane.showMessageDialog(rootPane, "Modification réussie",  "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_Modifier2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IdentifiantsSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IdentifiantsSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IdentifiantsSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IdentifiantsSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IdentifiantsSwing().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ajouter;
    private javax.swing.JButton Consulter;
    private javax.swing.JButton Modifier;
    private javax.swing.JButton Modifier2;
    private javax.swing.JButton Supprimer;
    private javax.swing.JTextField chLogin;
    private javax.swing.JTextField chMdp;
    private javax.swing.JTextField chNvxLogin;
    private javax.swing.JTextField chNvxMdp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelMdp;
    // End of variables declaration//GEN-END:variables
}
